image.registry: "docker.io"
image.repository: "bitnami/rabbitmq"
image.tag: 3.8.14

replicaCount: 3
persistence:
  enabled: true
  size: "10Gi"
  storageClass: ""
auth:
  username: "cloudrock"
  password: "cloudrock"

clustering:
  forceBoot: true
