apiVersion: v1
kind: ConfigMap
metadata:
  name: api-celery-config
data:
  celery.conf: |-
    # Cloudrock Celery configuration file
    #
    # See also: http://docs.celeryproject.org/en/latest/userguide/daemonizing.html

    CELERY_APP="cloudrock_core.server"

    CELERYBEAT_LOG_FILE="/var/log/cloudrock/celerybeat.log"
    CELERYBEAT_LOG_LEVEL="INFO"
    CELERYBEAT_OPTS=""
    CELERYBEAT_PID_FILE="/run/cloudrock/celerybeat/%n.pid"

    CELERYD_LOG_FILE="/var/log/cloudrock/celery-%n.log"
    CELERYD_LOG_LEVEL="INFO"
    CELERYD_CONCURRENCY=10
    CELERYD_OPTS="-Ofair -Q tasks,heavy,background"
    CELERYD_PID_FILE="/run/cloudrock/celery/%n.pid"

    #d /run/celery 0755 user users -
    #d /var/log/celery 0755 user users -
