{{ if has "CUSTOM" .Values.cloudrock.saml2.federations }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloudrock-idp-custom-metadata-config
data:
{{ $idpFile := .Values.cloudrock.saml2.dir | printf "%s/idp_metadata.xml" }}
  idp_metadata.xml: |-
{{ .Files.Get $idpFile | indent 4 }}
{{ end }}
