{{ if has "SAML2" .Values.cloudrock.authMethods }}
{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "21" ) }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: cloudrock-saml2-metadata-sync-cronjob
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cloudrock-saml2-metadata-sync
            image: {{ .Values.global.imageRegistry }}/{{ .Values.cloudrock.imageName }}:{{ .Values.cloudrock.imageTag }}
            imagePullPolicy: {{ .Values.cloudrock.pullPolicy }}
            args:
              - saml2-metadata-sync
            env:
              - name: GLOBAL_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: cloudrock-secret
                    key: GLOBAL_SECRET_KEY
              - name: POSTGRESQL_HOST
                value: {{ template "cloudrock.postgresql.host" . }}
              - name: POSTGRESQL_PORT
                value: {{ template "cloudrock.postgresql.port" . }}
              - name: POSTGRESQL_USER
                value: {{ template "cloudrock.postgresql.user" . }}
              - name: POSTGRESQL_NAME
                value: {{ template "cloudrock.postgresql.dbname" . }}
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ template "cloudrock.postgresql.secret" . }}
                    key: {{ template "cloudrock.postgresql.secret.passwordKey" . }}
              - name: LOGGING_LOG_FILE
                value: "/var/log/cloudrock/core.log"
              - name: EVENTS_LOG_FILE
                value: "/var/log/cloudrock/events.log"
              {{ if has "TAAT" .Values.cloudrock.saml2.federations }}
              - name: TAAT_METADATA_URL
                value: https://taeva.taat.edu.ee/metadata/metadata.taat+hub+prod+idp.xml
              {{ end }}
              {{ if has "EDUGAIN" .Values.cloudrock.saml2.federations }}
              - name: EDUGAIN_METADATA_URL
                value: http://md.incommon.org/InCommon/InCommon-metadata-idp-only.xml
              {{ end }}
              {{ if has "HAKA_TEST" .Values.cloudrock.saml2.federations }}
              - name: HAKA_TEST_METADATA_URL
                value: https://haka.funet.fi/metadata/haka_test_metadata_signed.xml
              {{ end }}
              {{ if has "HAKA_PROD" .Values.cloudrock.saml2.federations }}
              - name: HAKA_PROD_METADATA_URL
                value: https://haka.funet.fi/metadata/haka-metadata.xml
              {{ end }}
              {{ if .Values.cloudrock.sentryDSN }}
              - name: SENTRY_DSN
                value: {{ .Values.cloudrock.sentryDSN | quote }}
              {{ end }}
            volumeMounts:
              - name: api-override
                mountPath: /etc/cloudrock/override.conf.py
                subPath: override.conf.py
              - name: api-celery
                mountPath: /etc/cloudrock/celery.conf
                subPath: celery.conf
              - name: cloudrock-saml2-certs
                mountPath: /etc/cloudrock/saml2/credentials
              - name: cloudrock-saml2-conf
                mountPath: /etc/cloudrock/saml2.conf.py
                subPath: saml2.conf.py
              {{ if has "CUSTOM" .Values.cloudrock.saml2.federations }}
              - name: cloudrock-saml2-idp-metadata
                mountPath: /etc/cloudrock/saml2/metadata/idp_metadata.xml
                subPath: idp_metadata.xml
              {{ end }}
          volumes:
            - name: api-override
              configMap:
                name: api-override-config
            - name: api-celery
              configMap:
                name: api-celery-config
            - name: cloudrock-saml2-certs
              secret:
                secretName: cloudrock-saml2-secret
            - name: cloudrock-saml2-conf
              configMap:
                name: cloudrock-saml2-conf-config
            {{ if has "CUSTOM" .Values.cloudrock.saml2.federations }}
            - name: cloudrock-saml2-idp-metadata
              configMap:
                name: cloudrock-idp-custom-metadata-config
            {{ end }}
          restartPolicy: Never
{{ end }}
