{{ if .Values.cloudrock.uvkEverypay.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudrock-uvk-everypay
  labels:
{{ include "cloudrock.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: cloudrock-uvk-everypay
  template:
    metadata:
      labels:
        app: cloudrock-uvk-everypay
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $val := .Values.imagePullSecrets }}
        - name: {{ $val }}
        {{ end -}}
      {{ end }}
      containers:
      - name: cloudrock-uvk-everypay
        image: {{ .Values.global.imageRegistry }}/kubeworkz/cloudrock-uvk-everypay:latest
        imagePullPolicy: {{ .Values.cloudrock.pullPolicy }}
        env:
          - name: CLOUDROCK_API_URL
            value: "http://cloudrock-metal-api:8080/api/"
          - name: CLOUDROCK_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudrock-secret
                key: CLOUDROCK_STAFF_API_TOKEN
          - name: UVK_SERVER
            value: "{{ .Values.cloudrock.uvkEverypay.uvkServer }}"
          - name: EVERYPAY_GATEWAY
            value: "{{ .Values.cloudrock.uvkEverypay.everypayGateway }}"
          - name: EVERYPAY_USERNAME
            valueFrom:
              secretKeyRef:
                name: cloudrock-secret
                key: EVERYPAY_USERNAME
          - name: EVERYPAY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudrock-secret
                key: EVERYPAY_PASSWORD
          - name: CLOUDROCK_SIDECAR_URL
            value: {{ printf "%s://%s/uvk-everypay/" .Values.apiScheme .Values.apiHostname | quote }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      - name: cloudrock-uvk-everypay-sidecar
        image: {{ .Values.global.imageRegistry }}/kubeworkz/cloudrock-uvk-everypay-sidecar:latest
        imagePullPolicy: {{ .Values.cloudrock.pullPolicy }}
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        env:
          - name: CLOUDROCK_API_URL
            value: "http://cloudrock-metal-api:8080/api/"
          - name: CLOUDROCK_URL
            value: "{{ .Values.cloudrock-uiScheme }}://{{ .Values.cloudrock-uiHostname }}"
          - name: CLOUDROCK_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudrock-secret
                key: CLOUDROCK_STAFF_API_TOKEN
          - name: EVERYPAY_GATEWAY
            value: "{{ .Values.cloudrock.uvkEverypay.everypayGateway }}"
          - name: EVERYPAY_USERNAME
            valueFrom:
              secretKeyRef:
                name: cloudrock-secret
                key: EVERYPAY_USERNAME
          - name: EVERYPAY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudrock-secret
                key: EVERYPAY_PASSWORD
          - name: MAIL_SERVER
            value: {{ .Values.cloudrock.mail.host | quote }}
          {{ if .Values.cloudrock.mail.port }}
          - name: MAIL_PORT
            value: {{ .Values.cloudrock.mail.port | quote }}
          {{ end }}
          {{ if .Values.cloudrock.mail.username }}
          - name: MAIL_USERNAME
            value: {{ .Values.cloudrock.mail.username | quote }}
          {{ end }}
          {{ if .Values.cloudrock.mail.password }}
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudrock-secret
                key: MAIL_PASSWORD
          {{ end }}
          - name: MAIL_USE_TLS
            value: {{ .Values.cloudrock.mail.useTLS | quote }}
          - name: MAIL_USE_SSL
            value: {{ .Values.cloudrock.mail.useSSL | quote }}
          - name: MAIL_FROM
            value: {{ .Values.cloudrock.mail.from | quote }}
          - name: MAIL_REPLY_TO
            value: {{ .Values.cloudrock.mail.replyTo | quote }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{ end }}
