{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "19" ) }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: api-ingress-admin
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{ if .Values.ingress.tls.source | eq "letsEncrypt" }}
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    {{ end }}
    {{ if .Values.ingress.whitelistSourceRangeAdmin }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.whitelistSourceRangeAdmin }}"
    {{ else if .Values.ingress.whitelistSourceRange }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.whitelistSourceRange }}"
    {{ end }}
spec:
  rules:
  - host: {{ .Values.apiHostname }}
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: cloudrock-metal-api
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.apiHostname }}
    secretName: api-certificate
