{{ if .Values.cloudrock.marketplace.script.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudrock-script-kubeconfig
type: Opaque
data:
  kubeconfig: |-
{{ .Files.Get .Values.cloudrock.marketplace.script.kubeconfigPath | b64enc | indent 4 }}
{{ end }}