apiVersion: v1
kind: Secret
metadata:
  name: cloudrock-secret
type: Opaque
data:
  GLOBAL_SECRET_KEY: {{ .Values.cloudrock.secretKey | b64enc | quote }}
{{ if .Values.cloudrock.supportToken }}
  CLOUDROCK_SUPPORT_API_TOKEN: {{ .Values.cloudrock.supportToken | b64enc | quote }}
{{ end }}
{{ if .Values.cloudrock.staffToken }}
  CLOUDROCK_STAFF_API_TOKEN: {{ .Values.cloudrock.staffToken | b64enc | quote }}
{{ end }}
{{ if .Values.cloudrock.uvkEverypay.everypayUsername }}
  EVERYPAY_USERNAME: {{ .Values.cloudrock.uvkEverypay.everypayUsername | b64enc | quote }}
{{ end }}
{{ if .Values.cloudrock.uvkEverypay.everypayPassword }}
  EVERYPAY_PASSWORD: {{ .Values.cloudrock.uvkEverypay.everypayPassword | b64enc | quote }}
{{ end }}
{{ if .Values.cloudrock.mail.password }}
  MAIL_PASSWORD: {{ .Values.cloudrock.mail.password | b64enc | quote }}
{{ end }}
