{{ if .Values.cloudrock.ssh_private_key_path }}
kind: Secret
apiVersion: v1
metadata:
  name: cloudrock-ssh-key-config
type: Opaque
data:
  id_rsa: |-
{{ .Files.Get .Values.cloudrock.ssh_private_key_path | b64enc | indent 4 }}
{{ end }}
