{{ if has "SAML2" .Values.cloudrock.authMethods }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudrock-saml2-secret
type: Opaque
data:
{{ $certsDirTemp := .Values.cloudrock.saml2.dir | printf "%s/credentials/sp.crt" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ $certsDirTemp = .Values.cloudrock.saml2.dir | printf "%s/credentials/sp.pem" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ end }}
