apiVersion: v1
kind: Service
metadata:
  name: cloudrock-ui
  labels:
{{ include "cloudrock.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cloudrock-ui
