apiVersion: v1
kind: Service
metadata:
  name: cloudrock-metal-api
  labels:
{{ include "cloudrock.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cloudrock-metal-api
