{{ if .Values.cloudrock.uvkEverypay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cloudrock-uvk-everypay
  labels:
{{ include "cloudrock.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cloudrock-uvk-everypay
{{ end }}
